[build]
  command = "npm run build"
  publish = "dist"
  base = "."

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
